USE [master]
GO
/****** Object:  Database [user_data]    Script Date: 16/07/2024 1:44:21 CH ******/
CREATE DATABASE [user_data]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'user_data', FILENAME = N'E:\sqlllll\MSSQL16.SQLEXPRESS\MSSQL\DATA\user_data.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'user_data_log', FILENAME = N'E:\sqlllll\MSSQL16.SQLEXPRESS\MSSQL\DATA\user_data_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [user_data] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [user_data].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [user_data] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [user_data] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [user_data] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [user_data] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [user_data] SET ARITHABORT OFF 
GO
ALTER DATABASE [user_data] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [user_data] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [user_data] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [user_data] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [user_data] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [user_data] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [user_data] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [user_data] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [user_data] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [user_data] SET  ENABLE_BROKER 
GO
ALTER DATABASE [user_data] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [user_data] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [user_data] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [user_data] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [user_data] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [user_data] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [user_data] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [user_data] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [user_data] SET  MULTI_USER 
GO
ALTER DATABASE [user_data] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [user_data] SET DB_CHAINING OFF 
GO
ALTER DATABASE [user_data] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [user_data] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [user_data] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [user_data] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [user_data] SET QUERY_STORE = ON
GO
ALTER DATABASE [user_data] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [user_data]
GO
/****** Object:  Table [dbo].[users]    Script Date: 16/07/2024 1:44:21 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[users](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[full_name] [varchar](100) NOT NULL,
	[gender] [varchar](10) NOT NULL,
	[hobbies] [text] NULL,
	[job] [varchar](50) NULL,
	[username] [varchar](50) NOT NULL,
	[password] [varchar](255) NOT NULL,
	[email] [varchar](100) NOT NULL,
	[phone_number] [varchar](15) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[users] ON 
GO
INSERT [dbo].[users] ([id], [full_name], [gender], [hobbies], [job], [username], [password], [email], [phone_number]) VALUES (1, N'John Doe', N'male', N'fishing, walking', N'teacher', N'johndoe', N'password123', N'johndoe@example.com', N'123-456-7890')
GO
INSERT [dbo].[users] ([id], [full_name], [gender], [hobbies], [job], [username], [password], [email], [phone_number]) VALUES (2, N'Jane Smith', N'female', N'reading, swimming', N'student', N'janesmith', N'password456', N'janesmith@example.com', N'098-765-4321')
GO
SET IDENTITY_INSERT [dbo].[users] OFF
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__users__A1936A6B7CD983C7]    Script Date: 16/07/2024 1:44:21 CH ******/
ALTER TABLE [dbo].[users] ADD UNIQUE NONCLUSTERED 
(
	[phone_number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__users__AB6E6164F288EF97]    Script Date: 16/07/2024 1:44:21 CH ******/
ALTER TABLE [dbo].[users] ADD UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__users__F3DBC5722373442D]    Script Date: 16/07/2024 1:44:21 CH ******/
ALTER TABLE [dbo].[users] ADD UNIQUE NONCLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [user_data] SET  READ_WRITE 
GO
